### ISSUE TITLE
some question about convert_cycles_file

### ISSUE THREAD

**Issue by SeqCrafter** [jluebeck/CycleViz#10]
Can you help me understand the principle of `convert_cycles_file.py`? I found after running this script, my orignal cycle have more segments in it. and I don't know why. for example:

my raw cycle file is 

```
List of cycle segments
Segment	1	chr7	54659673	56169665
Segment	2	chr7	54763279	55127268
Segment	3	chr7	54961683	55127268
Segment	4	chr7	54961683	56169665
Segment	5	chr7	55155020	56049370
Segment	6	chr7	55155020	56169665
Segment	7	chr7	62941351	64855445
Segment	8	chr7	62941351	68306099
Segment	9	chr7	64857680	70955982
Segment	10	chr7	65489400	65498099
Segment	11	chr7	66728569	66729532
Segment	12	chr7	67002367	67021513
Segment	13	chr7	68708700	79383599
Segment	14	chr7	70216200	70638899
Segment	15	chr7	70961198	71746927
Segment	16	chr7	70973893	70973900
Segment	17	chr7	71274300	71746927
Segment	18	chr7	71747971	72805250
Segment	19	chr7	71747971	74135472
Segment	20	chr7	72822622	74414176
Segment	21	chr7	72940200	73015499
Segment	22	chr7	73113000	93787628
Segment	23	chr7	73967784	73967788
Segment	24	chr7	74136721	74414176
Segment	25	chr7	74416986	85761899
Segment	26	chr7	74416986	88051499
Segment	27	chr7	80120000	85761899
Segment	28	chr7	86130300	100901681
Segment	29	chr7	87631624	96846588
Segment	30	chr7	90450480	90459040
Segment	31	chr7	93288760	93453299
Segment	32	chr7	93793679	96846588
Segment	33	chr7	96852682	96913967
Segment	34	chr7	96917286	100716741
Segment	35	chr7	96917286	100901681
Segment	36	chr7	98046000	100716741
Segment	37	chr9	98005196	98345193
Cycle=1;Copy_count=82.7984824177;Segments=5+,2+
```

but later it becomes:

```
Cycle=1;Copy_count=82.7984824177;Length=1258Kbp;Segments=5+,6+,7+,2+,3+;Circular=TRUE;TRIVIAL=TRUE
```

and my cycle 1 plot is 
![cycle1](https://s3.ax1x.com/2021/03/16/6s1xBR.png)

Why are the coordinates on the graph out of order? What do black lines and gray arrows mean？

**Comment by jluebeck** [comment]
Hi, 

The conversion step for the cycles file changes the segment numbering to use the segments in the AA graph file instead of the cycles file (you'll note the segments are different between the two). 

The grey coordinates are reference coordinates scaled down by 10kbp. The black lines indicate gene regions. The grey triangle indicates gene start, the grey square indicates gene end. Exons are indicated at positions where the black line is wider.

I hope this is helpful!

Best,
Jens

**Comment by SeqCrafter** [comment]
so, if I want to get one ecc, I should use the segments from cycleViz cycle file other than AA cycle file?

**Comment by jluebeck** [comment]
If I understand the question correctly - in order to run CycleViz on AA output, you will need to run the script `convert_cycles_file.py`, which divides the AA cycles file segment endpoints to match the endpoints present in the graph file - simplifying the accounting process which CycleViz needs to do.

Best,
Jens

**Comment by SeqCrafter** [comment]
> If I understand the question correctly - in order to run CycleViz on AA output, you will need to run the script `convert_cycles_file.py`, which divides the AA cycles file segment endpoints to match the endpoints present in the graph file - simplifying the accounting process which CycleViz needs to do.
> 
> Best,
> Jens

Sorry maybe I have some misunderstanding about cycleViz. If I understand it correctly, the segment from cycle1 of AA's cycle file is the eccDNA region I want to look for in the genome. But after running  `convert_ cycles_ file.py` , I got more segments like 6,7,and 3. So if I want to get the correct eccDNA region of cycle 1, should it be 5 + 2 or 5 + 6 + 7 + 2 + 3

**Comment by jluebeck** [comment]
Hi,

Good question - please note that the segments themselves are re-labeled in the two files. If you compare the original AA cycles file segments with the converted cycles file segments, you will typically find that the segments have been broken into smaller pieces in the later, and thus there are a greater number of segments. The conversion is just a breaking and relabeling of existing segments to remove overlaps from different segments. The structure of the cycle in the genome is identical between original and converted, just how the structure is represented in terms of the labeling of segments from the reference is different.

Best,
Jens

**Comment by SeqCrafter** [comment]
Oh, it's my fault. I didn't find their coordinates changed. I'm sorry to ask such a stupid question.
