### ISSUE TITLE
Sample YAML file?

### ISSUE THREAD

**Issue by tischfis** [jluebeck/CycleViz#12]
Is there a sample YAML file one could use as a reference?

**Comment by jluebeck** [comment]
Hi, yes - here is the default YAML for a basic case: https://github.com/jluebeck/CycleViz/blob/master/resources/default_CV.yaml.

Please give me a couple days and I will add a worked example using multiple annotation tracks, so users can have a more complete jumping-off point.

Thanks,
Jens

**Comment by tischfis** [comment]
Ah, sorry, i just missed it in that directory.  Thank you!
