### ISSUE TITLE
Missing file in the example

### ISSUE THREAD

**Issue by shwong-tw** [jluebeck/CycleViz#15]
Hi Jens,
Just a very minor report: I'd like to run T41 example but the _T41_amplicon1_graph.txt_ file is missing in the directory.
Thanks a lot!

**Comment by jluebeck** [comment]
Thanks for catching that, and my apologies. I had them in the .gitignore file. Added graph files for examples in [3913627](https://github.com/AmpliconSuite/CycleViz/commit/39136276500debdd6458f4515e125d592bf810d7).

Cheers,
Jens
