### ISSUE TITLE
interpreting the results of CycleViz

### ISSUE THREAD

**Issue by eesiribloom** [jluebeck/CycleViz#17]
I am struggling to _completely_ understand the differences of the outputs in AA and AC and how to translate this to presenting the results of the analysis:
If I have an individual sample which appears to have ecDNA how should I understand the results of having say: 

Several amplicons from AA, some of which might contain "ecDNA" according to AC and multiple ecDNA-like cycles. 

I understand AC merges overlapping cycles/paths to estimate what might be an ecDNA. Firstly, what is an "amplicon" in comparison to the, anywhere from 1-5 or so, ecDNA contained within that output from AC. Within this there are several"ecDNA-like" cycles/paths...which I am a bit confused about. Are these ecDNA reported by AC then considered distinct? If I have a sample which has e.g. two ecDNA-containing amplicons, one with 5 ecDNAs and one with 1 ecDNA, should I interpret this single sample to contain 6 distinct ecDNA species? essentially, what is the level of resolution where I might say "this sample has this particular ecDNA made up of this particular genomic region/intervals" - would it be the amplicon, the ecDNA, or the cycle?

**Comment by eesiribloom** [comment]
Apologies I am going to repost this issue on Amplicon Classifier as that is more appropriate, feel free to delete this isssue here.

**Comment by jluebeck** [comment]
No problem -
Discussion moved here: https://github.com/AmpliconSuite/AmpliconClassifier/issues/18
